# Nivel 1
## Exercici 1
Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu. .

In [11]:
import numpy as np
arr = np.array([109, 2098, 3, 14, 9875, 1234, 27, 6, 1977])
print(arr)
print('La dimensión del array es: ',arr.ndim)
print(arr.shape)

[ 109 2098    3   14 9875 1234   27    6 1977]
La dimensión del array es:  1
(9,)


## Exercici 2
De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts.

In [10]:
import numpy as np
arr = np.array([109, 2098, 3, 14, 9875, 1234, 27, 6, 1977])
print("La media de arr es: ", np.mean(arr))

La media de arr es:  1704.7777777777778


## Exercici 3
Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [28]:
import numpy as np
arr = np.array([[109, 2098, 3, 14, 9875],[1977, -4, 1234, 27, 6], [2,4,5,7,8], [4,0,0,-3,1], [4,6,7,12,1345]])
print(arr)
print('El valor máximo de la matriz es: ', np.amax(arr))
print('El valor máximo de cada columna es: ',np.max(arr, axis=0))
print('El valor máximo de cada fila es: ',np.max(arr, axis=1))


[[ 109 2098    3   14 9875]
 [1977   -4 1234   27    6]
 [   2    4    5    7    8]
 [   4    0    0   -3    1]
 [   4    6    7   12 1345]]
El valor máximo de la matriz es:  9875
El valor máximo de cada columna es:  [1977 2098 1234   27 9875]
El valor máximo de cada fila es:  [9875 1977    8    4 1345]


---

# Nivel 2

## Exercici 4
Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".

## Exercici 5

Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.

## Exercici 6
Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre.

Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.

## Exercici 7
A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però encara obteniu les dades que esteu cercant.

---

# Nivel 3

## Exercici 8
Mostreu-me a veure que passa quan eliminem el canal G Verd o B Blau.

Mostreu-me a veure què passa quan eliminem el canal G Verd o B Blau. Hauries d'utilitzar la indexació per seleccionar el canal que voleu anul·lar.

Utilitzar el mètode, mpimg.imsave () de la llibreria importada, per guardar les imatges modificades i que haureu de pujar al vostre repositori a github.